import {PERMISSIONS} from 'react-native-permissions';

export enum PermissionEnum {
  CAMERA = 'CAMERA',
  READ_MEDIA_IMAGES = 'READ_MEDIA_IMAGES',
  READ_MEDIA_VISUAL_USER_SELECTED = 'READ_MEDIA_VISUAL_USER_SELECTED',
  CONTACTS = 'CONTACTS',
  ACCESS_MEDIA_LOCATION = 'ACCESS_MEDIA_LOCATION',
  CALL_PHONE = 'CALL_PHONE',
  GET_ACCOUNTS = 'GET_ACCOUNTS',
  READ_CONTACTS = 'READ_CONTACTS',
  READ_PHONE_NUMBERS = 'READ_PHONE_NUMBERS',
  ACCESS_FINE_LOCATION = 'ACCESS_FINE_LOCATION',
}

// Define the type for permissions using the typeof and keyof operators
type AndroidPermission =
  (typeof PERMISSIONS.ANDROID)[keyof typeof PERMISSIONS.ANDROID];

export const permissionMap: {[key in PermissionEnum]: AndroidPermission} = {
  [PermissionEnum.CAMERA]: PERMISSIONS.ANDROID.CAMERA,
  [PermissionEnum.READ_MEDIA_IMAGES]: PERMISSIONS.ANDROID.READ_MEDIA_IMAGES,
  [PermissionEnum.READ_MEDIA_VISUAL_USER_SELECTED]:
    PERMISSIONS.ANDROID.READ_MEDIA_VISUAL_USER_SELECTED,
  [PermissionEnum.CONTACTS]: PERMISSIONS.ANDROID.READ_CONTACTS,
  [PermissionEnum.ACCESS_MEDIA_LOCATION]:
    PERMISSIONS.ANDROID.ACCESS_MEDIA_LOCATION,
  [PermissionEnum.CALL_PHONE]: PERMISSIONS.ANDROID.CALL_PHONE,
  [PermissionEnum.GET_ACCOUNTS]: PERMISSIONS.ANDROID.GET_ACCOUNTS,
  [PermissionEnum.READ_CONTACTS]: PERMISSIONS.ANDROID.READ_CONTACTS,
  [PermissionEnum.READ_PHONE_NUMBERS]: PERMISSIONS.ANDROID.READ_PHONE_NUMBERS,
  [PermissionEnum.ACCESS_FINE_LOCATION]:
    PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
};
